apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dg0ne/todo-web-gitops.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-web
  syncPolicy:
    automated: null
      #prune: true
      #selfHeal: true
    syncOptions:
    - CreateNamespace=true
